#!/usr/bin/env bash
# A function to query DNS

query_dns() {
    local domain="$1"
    local subdomain="$2"

    local answer_section=$(dig "$subdomain.$domain" +short)

    local record_type=$(dig "$subdomain.$domain" +short -t ANY)

    echo "The subdomain $subdomain is a $record_type record and points to $answer_section"
}

domain="$1"
subdomain="$2"

for sub in "www" "lb-01" "web-01" "web-02"; do
	if [ -z "$subdomain" ] || [ "$subdomain" == "$sub" ]; then
		query_dns "$domain" "$sub"
	fi
done
