#!/usr/bin/env bash
#Checks if script is provided with correct number of parameters
#Asigns parameters to variables for clarity
#Uses scp to transfer file to users home directory on the server

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi


file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~

if [ $? -eq 0 ]; then
    echo "File '$file_path' has been successfully transferred to the server."
else
    echo "Error: File transfer failed."
fi
