#!/usr/bin/env bash
#Configures an ubuntu server with a HTTP header
# Allow nginx through firewall

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo sed -i "25i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf

sudo service nginx reload
sudo service nginx restart
