#!/usr/bin/env bash
# Configures HAProxy on 1b-01 load balance traffic to web-01 and web-02
# Updates package information

sudo apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL

frontend http-in
   bind *:80
   mode http
   default_backend servers
   timeout client 30s
   timeout server 30s
   timeout connect 5s

backend servers
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   timeout client 30s
   timeout server 30s
   timeout connect 5s
   server 261084-web-01 18.209.223.53:80 check
   server 261084-web-02 54.160.76.99:80 check
EOL


sudo service haproxy restart
