#!/usr/bin/env bash
# Configures HAProxy on 1b-01 load balance traffic to web-01 and web-02
# Updates package information

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 261084-web-01	18.209.223.53 check
   server 261084-web-02	54.160.76.99 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
