#!/usr/bin/env bash
#The script configures /etc/hosts for localhost and facebook.com

cp /etc/hosts ~/hosts.backup
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.backup
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.backup
cp -f ~/hosts.backup /etc/hosts
