#!/usr/bin/env bash
# Fixes the container for nginx to run as nginx user and not root
# Stop apache2 if it's running
# Update server block to listen on 8080
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf

sudo pkill 'apache2'

sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default

sudo -u service nginx restart
