#!/usr/bin/env bash
# Fixes the container for nginx to run as nginx user and not root
# Stop apache2 if it's running
# Update server block to listen on 8080
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

pkill apache2

sed -i 's/80/8080/g' /etc/nginx/sites-available/default

sudo -u nginx service nginx start
