#!/usr/bin/env bash
# Fixes the container to run as nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo service apache2 stop
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo service nginx restart
