#!/usr/bin/env bash
# Fixes the container to run as nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo pkill 'apache2'
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u service nginx restart
