#!/usr/bin/env bash
#Config file to run backend using flask

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name 18.209.223.53;
        add_header X-Served-By XX-web-01;

        location /airbnb-onepage/ {
                proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }

        location /airbnb-dynamic/number_odd_or_even/ {
                proxy_pass http://127.0.0.1:5001/number_odd_or_even/;
        }

        error_page 404 /404.html;
        location /404 {
                root /var/www/html;
                internal;
        }
}
