#!/usr/bin/env bash
#Rendering Airbnb v4 config
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name 18.209.223.53;
        add_header X-Served-By XX-web-01;

        location /airbnb-onepage/ {
                proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }

        location /airbnb-dynamic/number_odd_or_even/ {
                proxy_pass http://127.0.0.1:5001/number_odd_or_even/;
        }

        #Serving AirBnB_clone_v3 API
        location /api {
                proxy_pass http://127.0.0.1:5002/api;
        }

        # Configures /2-hbnb route of Airbnb v4 as root location
        location / {
                proxy_pass http://127.0.0.1:5003/2-hbnb;
        }

        # Serving static content for Airbnb v4
        location /static {
                alias web_dynamic/static/;
        }

        error_page 404 /404.html;
        location /404 {
                root /var/www/html;
                internal;
        }
}
